### ISSUE TITLE
import objects from "@permaweb/aoconnect" get error in a Next.js project when using NextJS App Router

### ISSUE THREAD

**Issue by iamgamelover** [permaweb/ao#526]
Hello everyone,

I used `import { createDataItemSigner, message, dryrun } from "@permaweb/aoconnect";` in a Next.js project.
Running on localhost, get an error on the browser page.
```
./node_modules/@permaweb/aoconnect/dist/index.js
Attempted import error: 'warp-arbundles' does not contain a default export (imported as 'WarpArBundles').
```
I changed to `const { createDataItemSigner, message, dryrun } = require("@permaweb/aoconnect");` and it's working.
But when I'm deploying it to vercel.com, get a new error on the vercel deploy page:
```
TypeError: Cannot assign to read only property 'name' of function 'class A extends Error{static{this.name="InvalidSchedulerLocation"}constructor(...e){super(...e),this.name=A.name}}'
--
 at <static_initializer> (/vercel/path0/.next/server/app/testao/page.js:34:124266)
at 25290 (/vercel/path0/.next/server/app/testao/page.js:34:124244)
at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
at 8672 (/vercel/path0/.next/server/app/testao/page.js:69:2159)
at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
```
Anybody can give me some advices? Thanks.

**Comment by TillaTheHun0** [comment]
Hey @iamgamelover , sorry you're having issues.

Both of these issues are downstream from NextJS' config. The first issue is most likely due to NextJS webpack config -- `aoconnect` is not importing a default export from `warp-arbundles`. This is the line in `aoconnect/dist/index.js`:

```js
import * as WarpArBundles from "warp-arbundles";
var { createData, ArweaveSigner } = WarpArBundles;
```

I suspect something with NextJS webpack config is trying to support the myriad of ESM+CJS combinations that exist in NodeJS ecosystem, and is getting tongue tied. Sounds like the `require` get's around that issue though.

The seconds issue is an error in NextJS' static code analysis (also being done by Webpack, it seems). It's claiming that read-only property `name` cannot be reassigned, in relation to [this error class](https://github.com/permaweb/ao/blob/a6d0d1bb4a2d868002b9e5da2a517127b65aef4a/scheduler-utils/src/err.js#L1)

But this is definitely valid using [static members](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#telling_the_constructor_name_of_an_object).

Maybe there's a way to suppress the static check with NextJS?

**Comment by TillaTheHun0** [comment]
fixed by changes in #527 . Closing.

**Comment by iamgamelover** [comment]
Thank you, Sir!
I also downgrade the NextJS to v13.5.6 to solve this problem. Used v14 before. :-)

**Comment by TillaTheHun0** [comment]
@iamgamelover we determined that an issue only occurs when using NextJS' "App Router". 

So another workaround is to not use App Router and instead use conventional API routes. That worked with the latest version of NextJS.

We'll need to investigate the deal with App Router, but that seems to be the source of the issue.

**Comment by TillaTheHun0** [comment]
Reopening. The original issue was solved, but it unveiled another issue when using NextJS' App Router.

**Comment by Merdi-kim** [comment]
<img width="1440" alt="Screenshot 2024-03-19 at 18 14 17" src="https://github.com/permaweb/ao/assets/70149872/b83c24e7-7116-4f1b-b622-32c54c4ed595">

Adding the screenshot just for reference

**Comment by Merdi-kim** [comment]
next.js version `13.5.6` seems to be working. Thanks to @iamgamelover 's answer

**Comment by Merdi-kim** [comment]
But I can help investigate the issue with next.js 14 and see if there are workarounds without downgrading

**Comment by femaury** [comment]
Hey @Merdi-kim @TillaTheHun0 has any progress been made on this? Happy to help if I can, would love to not have to downgrade or go back to the pages api 😄 

I was digging through the AO discord and there was some talk about this PR https://github.com/warp-contracts/warp/pull/514 potentially helping things? Haven't been able to find how it relates to this exactly though...

**Comment by TillaTheHun0** [comment]
@TillaTheHun0 afaik, no progress has been made on this. It's definitely something to do with NextJS App Router, as using NextJS "conventional" api routes works, even on latest versions of NextJS.

Re: PR to warp: `aoconnect` doesn't use warp, but it uses [`warp-arbundles`](https://github.com/warp-contracts/warp-arbundles) which is a lightweight ANS-104 implementation. The idea was maybe submitting a PR to `warp-arbundles` like the PR there submitted to `warp`, since it seems to be a similar issue. I'm not sure if anyone is currently tracking that down.

**Comment by jrdn91** [comment]
As far as I can tell, this is an issue with Webpack which is what Next.js uses under the hood. There is an open issue with little traction on the Next.js repo here https://github.com/vercel/next.js/discussions/49120

And there are some other discussions that are giving some extra context

https://github.com/vercel/next.js/issues/32714
https://github.com/webpack/webpack/issues/4674

One fix is to simply append `/browser` to the end of the import which forces the module resolution to resolve to a specific file instead of using it's resolution logic to determine which field is best. That looks something like this

```
...
import { createDataItemSigner, message } from "@permaweb/aoconnect/browser";
...
```

However, you can edit the next.config.mjs file to "rewrite" the package to point to browser so you don't have to edit this each time, and so that auto import can keep working as normal...

```
...
const nextConfig = {
  webpack: (config, { isServer }) => {
    // Add the alias to the webpack configuration
    config.resolve.alias["@permaweb/aoconnect"] = path.resolve(
      process.cwd(), // __dirname is not available in all environments this may run in
      "node_modules/@permaweb/aoconnect/dist/browser"
    );

    // Return the modified config
    return config;
  },
};
...
```
