### ISSUE TITLE
chore(cu): remove SU legacy mapping from CU once new SUs are live

### ISSUE THREAD

**Issue by TillaTheHun0** [permaweb/ao#570]
Depends on #563 being deployed and #569 being merged and deployed on CUs

Once the SUs serving up the new shape are deployed, the CUs will no longer need to interop between the legacy shape and new shape. At that point the SU legacy mapping code can be removed, specifically in `loadMessageMetaWith` and `loadMessagesWith` in the `ao-su` client. Accompanying tests for legacy mapping can also be removed.

This should be considered work to remove technical debt in the CU.

Severity of technical debt: **low**
Hard deadline for removing technical debt to prevent disruption: **no hard deadline**

## Acceptance Criteria

- [x] dead code for legacy mapping is removed in `loadMessagesWith` and associated tests
- [x] dead code for legacy mapping is removed in `loadMessageMetaWith` and associated tests
- [x] remaining tests for "new shape" still pass

## Developer Notes

The changes should be almost entirely removing dead code and associated branching and tests.

**Comment by VinceJuliano** [comment]
Regarding this issue, currently the SU is returning both the old and the new shape. It will return the old shape for messages that were uploaded before the aopv0.1 release. But everything after that is the new shape. If we want to return always the new shape we will need another code change. If we keep it the way it is all old processes would eventually have to be obsolete in order to remove the legacy support in the SU.
