### ISSUE TITLE
Ao-evaluation-test.js saveEvaluationWith test seems invalid

### ISSUE THREAD

**Issue by jsoneaday** [permaweb/ao#695]
Some of the tests inside of the "saveEvaluation" describe section seem to have an invalid output value. If the args output is output: { Messages: [{ foo: 'bar' }], Memory: 'foo' } How can the test assert for { Messages: [{ foo: 'bar' }] }

<img width="1444" alt="Screenshot 2024-05-10 at 4 43 59 PM" src="https://github.com/permaweb/ao/assets/1474935/a065b7b3-e72a-4223-8f18-8feb4f241d8b">
<img width="768" alt="Screenshot 2024-05-10 at 4 42 33 PM" src="https://github.com/permaweb/ao/assets/1474935/775585c0-e74d-4bb1-a7d7-7401ad4439fc">
<img width="1318" alt="Screenshot 2024-05-10 at 4 42 02 PM" src="https://github.com/permaweb/ao/assets/1474935/e3f1cb06-3d51-463b-928e-1537cdb62872">

**Comment by TillaTheHun0** [comment]
Great question. Because the `evaluationDocSchema` [explicitly omits `Memory` from `output`](https://github.com/permaweb/ao/blob/0afaa876a16ab4d884ce4c7b096d7452fc549ae8/servers/cu/src/domain/client/ao-evaluation.js#L20). Furthermore that's the reason the stub and assertion is what it is, to ensure `Memory` _is_ being omitted.

**Comment by TillaTheHun0** [comment]
Closing this out. Please feel free to ask more questions here or on ao Discord.
