### ISSUE TITLE
 MU sometimes receives incorrect empty result from CU

### ISSUE THREAD

**Issue by tzarebczan** [permaweb/ao#773]
This message included a handler that ran an assign to an aggregate process, with the original message id (msg.Id) to pass into the assignment. 

https://cu7.ao-testnet.xyz/result/B9erAmSP8rypZLJS2p7Zj9kJA6BCEGPK1oRC1tjcuOY?process-id=USeBAOJjR-7F6mfre3VzBmFZhsWb42kdyeuvSugi5T8

You can see this :    ```
"Assignments": [
        {
            "Message": "B9erAmSP8rypZLJS2p7Zj9kJA6BCEGPK1oRC1tjcuOY",
            "Processes": [
                "-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0"
            ]
        }
    ]```

This is the assignment message: https://www.ao.link/message/d99jzHyGs3A_EEXNbW52KEKiBoBqevvdcivY74j8FTM but nothing is ever processed on `-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0`: https://www.ao.link/entity/-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0

https://cu.ao-testnet.xyz/result/d99jzHyGs3A_EEXNbW52KEKiBoBqevvdcivY74j8FTM?process-id=-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0 - this transaction never made it onto arweave layer 1.

**Comment by keikari** [comment]
Similar issue turned up with other assignment. This is result to message being assigned to process, but the output message never made it to Arweave.  
https://cu.ao-testnet.xyz/result/aQwOzUrY1CKj10bKMWd5QxZ8yPdho_RQ5D1uwKJ5jvA?process-id=-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0

Looks like the MU has problem with one of the values being a number
![2024-06-06_19-41](https://github.com/permaweb/ao/assets/34790748/d8dd4317-49eb-4b8a-a738-ad87bfd16a38)

**Comment by keikari** [comment]
Steps to see the issue. The issue seems to happen ~90% of the time. Few times I saw it work as expected:
1. Create process A
2. Add handler to process A
```
Handlers.add(
        "test-action",
        Handlers.utils.hasMatchingTag("Action", "Test-Action"),
        function (m)
            ao.send({Target = m.From, Data= "This message will never be created"})
        end
)
```
3. Create process B
4. Add handler to process B
```
Handlers.add(
        "test-action",
        Handlers.utils.hasMatchingTag("Action", "Test-Action"),
        function (m)
            ao.assign({Processes = { PROCESS_A_PID }, Message = m.Id})
        end
)
```

5. From process B enter
```
Send({Target = ao.id, Action = "Test-Action"})
```

Result:
 Message created in the handler in the process A is generated in the outbox, but it never gets send to Arweave.
 Issue seems to be that MU gets empty response when it checks that result.
 
 <details>
<summary> Screenshot from MU with empty response to assignment that generated  result</summary>

Link from the screenshot: https://cu.ao-testnet.xyz/result/ssswMSaMAnBTPePuEZMMVVHhWfPbAu8NW1MIzDaat2E?process-id=8fqIU38gHr06EqURPj80VNbIn-W436oQZa2UZ5WE7-0&no-busy=1

![2024-06-07_11-09](https://github.com/permaweb/ao/assets/34790748/e8451a40-be81-48d1-a9d5-926ba28d8183)

 </details>

**Comment by twilson63** [comment]
Just a quick look and I could be wrong, but it looks like you are trying to
send a message that has already been assigned for that process.

For example if you send Message A to Process A, by using Send, then you
can't assign Message. A to Process A, it will ignore any attempts to assign
Message A to Process A again.

**Comment by keikari** [comment]
This is different.  
At the time of the original issue, there was some confusion about what's happening. And it turned out that the assigning part actually seems to work fine, but the message resulting from that never reached Arweave. 

This may not actually be related to assigning, but those steps just seems to be repro-able

In the repro steps, at the end, the MU gets empty result from the CU result link. But if the link is checked now, it can be seen that there is a outputted message there, but this one never reached Arweave (See screenshot of MU)
Forgot to mention that, and link to the result got hidden with the screenshot.

**Comment by tzarebczan** [comment]
Also more context: We're sending the message to B, not A. 

What we're trying to show here is something like this flow:
Message 1 to Process B > Assigns Message 1 to Process A > Process A sends reply to Process B (msg.From from Message 1)

**Comment by keikari** [comment]
For some reason this link in the second message returns now an empty result. It definitively had a new message there before.    
https://cu.ao-testnet.xyz/result/ssswMSaMAnBTPePuEZMMVVHhWfPbAu8NW1MIzDaat2E?process-id=8fqIU38gHr06EqURPj80VNbIn-W436oQZa2UZ5WE7-0&no-busy=1  

<details>
<summary>Screenshot of the empty result, in case it changes back</summary>

![2024-06-08_12-18](https://github.com/permaweb/ao/assets/34790748/b23671c2-a14d-4bb7-a2b2-3469d77bdcf2)

</details>

------------------------- 

Here is a new link+screenshots showing the issue. (Also a screenshot of what I see when checking CU manually, in case it changes again. )
https://cu.ao-testnet.xyz/result/rzu6lIyxSVIlL6zvUZZ7Wxj1kzjyZp9HfNuYhfWYA5c?process-id=tzMcL9smF0Z-HbzM9Fr8TfYsPx4wSUSiG676lViyORc&no-busy=1  

Can see a new message in results, but at the time MU checked the same link it didn't see the message. And message didn't made it to Arweave.  
<details>
<summary>Screenshots</summary>

![2024-06-08_12-00](https://github.com/permaweb/ao/assets/34790748/c2791d16-d6f4-4321-9db1-9885a37929e8)

![2024-06-08_12-00_1](https://github.com/permaweb/ao/assets/34790748/1614cd87-e80d-4411-833f-4483e55bdb76)
</details

**Comment by tzarebczan** [comment]
I'm going to close this and open a new issue now that we've isolated the root cause more.
