### ISSUE TITLE
feat(images): make docker images public

### ISSUE THREAD

**Issue by dtfiedler** [permaweb/ao#868]
## Details
You're publishing docker images for MU/CU/SU to ghcr 👏 , but they are not public or available for use 😞 .

Action: https://github.com/permaweb/ao/actions/runs/9809709838/job/27088255462

## Suggestion
Make the packages public so those experimenting with running the AO stack can pull the latest images

**Comment by dtfiedler** [comment]
Related PR - https://github.com/permaweb/ao/pull/648

**Comment by TillaTheHun0** [comment]
CU and MU packages are made public. SU package is currently not publishing due to an error in the build that needs to be fixed: https://github.com/permaweb/ao/issues/683.

There are no guarantees or first tier support for using these images, as the implementations and data protocol are still under active development. See [here](https://github.com/permaweb/ao?tab=readme-ov-file#self-hosting-an-ao-unit). These images are solely made available for the sake of convenience, transparency, and experimentation.

Thanks again for help with this @dtfiedler . Closing this out, but let me know if I missed something, and happy to re-open
